/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/diagnostics`; params?: Router.UnknownInputParams; } | { pathname: `/garage`; params?: Router.UnknownInputParams; } | { pathname: `/garage/new`; params?: Router.UnknownInputParams; } | { pathname: `/maintenance`; params?: Router.UnknownInputParams; } | { pathname: `/maintenance/new`; params?: Router.UnknownInputParams; } | { pathname: `/manuals`; params?: Router.UnknownInputParams; } | { pathname: `/chat/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/garage/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/maintenance/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/diagnostics`; params?: Router.UnknownOutputParams; } | { pathname: `/garage`; params?: Router.UnknownOutputParams; } | { pathname: `/garage/new`; params?: Router.UnknownOutputParams; } | { pathname: `/maintenance`; params?: Router.UnknownOutputParams; } | { pathname: `/maintenance/new`; params?: Router.UnknownOutputParams; } | { pathname: `/manuals`; params?: Router.UnknownOutputParams; } | { pathname: `/chat/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/garage/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/maintenance/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/diagnostics${`?${string}` | `#${string}` | ''}` | `/garage${`?${string}` | `#${string}` | ''}` | `/garage/new${`?${string}` | `#${string}` | ''}` | `/maintenance${`?${string}` | `#${string}` | ''}` | `/maintenance/new${`?${string}` | `#${string}` | ''}` | `/manuals${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/diagnostics`; params?: Router.UnknownInputParams; } | { pathname: `/garage`; params?: Router.UnknownInputParams; } | { pathname: `/garage/new`; params?: Router.UnknownInputParams; } | { pathname: `/maintenance`; params?: Router.UnknownInputParams; } | { pathname: `/maintenance/new`; params?: Router.UnknownInputParams; } | { pathname: `/manuals`; params?: Router.UnknownInputParams; } | `/chat/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/garage/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/maintenance/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/chat/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/garage/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/maintenance/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
